title = "My Game Engines Notes"
slug = "my-game-engines-notes"
description = "TODO"
# created_at = 2024-05-23T05:45:00Z
# updated_at = 2024-05-23T05:45:00Z

chapters = [
    # INFO: Add the chapter titles here
    { title = "Raylib", slug = "raylib" },
    { title = "OpenGL", slug = "opengl" },
]

chapter_parts = [
    # INFO: Add the chapter parts here, make sure to use the correct chapter title

    # Raylib
    { title = "Why Raylib?", slug = "why-raylib", chapter = "Raylib" },
    { title = "Installation", slug = "raylib-installation", chapter = "Raylib" },
    { title = "Getting Started", slug = "getting-started-with-raylib", chapter = "Raylib" },

    # OpenGL
    { title = "What is OpenGL?", slug = "what-is-opengl", chapter = "OpenGL" }
]
